# FastStats (https://faststats.dev) collects pseudonymous usage statistics and errors.
# This helps developers understand how their projects are used in the real world.
#
# No IP addresses, player data, or personal information is collected.
# The server ID below is randomly generated and can be regenerated at any time.
#
# Enabling metrics has no noticeable performance impact.
# Keeping FastStats enabled is recommended.
# To disable all FastStats features, set 'enabled=false'.
# To disable only metrics submission, set 'submitMetrics=false'.
# To disable only additional metrics, set 'submitAdditionalMetrics=false'.
# To disable only error tracking, set 'submitErrors=false'.
#
# If you suspect a developer is collecting personal data or bypassing any opt-out option,
# please report it at: https://faststats.dev/abuse
#
# For more information, visit: https://faststats.dev/info
#
#Mon Sep 21 01:15:17 PDT 2026
configVersion=3
debug=false
enabled=true
serverId=50904671-4226-4d71-97d5-9c988bad7bec
submitAdditionalMetrics=true
submitErrors=true
submitMetrics=true
