#Default Server Listings Configuration
#Each entry should be a config object with the following fields:
#  - name: The display name of the server
#  - address: The IP address or domain of the server
#  - resourcePackStatus: The resource pack status (ENABLED, DISABLED, PROMPT)
[config]
	#Enable or disable the Default Server Listings mod
	enabled = true
	#Server List Entries
	[[config.serverListings]]
		name = "Station48 Cobblemon"
		resourcePackStatus = "ENABLED"
		address = "play.station48.xyz"
