#Pokestops Configuration
[pokestopsConfig]
	#List of extra rarities to be used in the Pokestops mod. Default is an empty list.
	extraRarities = ["cobblemon:master_ball", "cobblemon:ancient_origin_ball", "cobblemon:ability_capsule", "cobblemon:max_revive", "cobblemon:hyper_potion", "cobblemon:ultra_ball", "cobblemon:master_rod"]

#Broadcast Settings
[broadcastSettings]
	#Whether to enable global broadcast for Pokestops. Default is false.
	enableGlobalBroadcast = false
	#The radius in blocks for local broadcast of Pokestops. Default is 50.0 blocks.
	# Default: 50.0
	# Range: 1.0 ~ 1.7976931348623157E308
	localBroadcastRadius = 50.0

#Cooldown Settings
[cooldownSettings]
	#The cooldown in seconds for Pokestops. Default is 300 seconds.
	# Default: 300
	# Range: > 1
	pokestops = 300
	#The cooldown in seconds for Winged Stops. Default is 300 seconds.
	# Default: 300
	# Range: > 1
	wingedstops = 300
	#The cooldown in seconds for Pokeball Stops. Default is 300 seconds.
	# Default: 300
	# Range: > 1
	pokeballstops = 300
	#The cooldown in seconds for Healing Stops. Default is 600 seconds.
	# Default: 600
	# Range: > 1
	healingstops = 600

#Stop Remover Configuration
[stopRemoverConfig]
	#Whether the Stop Remover requires OP privileges to use. Default is false.
	requireOp = false
	#The permission level required to use the Stop Remover. Default is NONE.
	#Allowed Values: NONE, SPAWN_PROTECTION_BYPASS, CHEAT_COMMANDS_AND_COMMAND_BLOCKS, MULTIPLAYER_MANAGEMENT, ALL_COMMANDS
	permissionLevel = "NONE"
	#Whether the Stop Remover drops the stop item when used. Default is false.
	dropsStopItem = false
	#The number of seconds for the confirmation window when using the Stop Remover. Default is 5 seconds.
	# Default: 5
	# Range: > 1
	confirmWindowSeconds = 5
